-- begin COUNTRY
create unique index IDX_Country_UK_name on Country (name) where DELETE_TS is null ^
-- end COUNTRY
-- begin GENPRO_DOC
alter table GENPRO_DOC add constraint FK_GENPRO_DOC_ON_CITIZENSHIP foreign key (CITIZENSHIP_ID) references Country(ID)^
create index IDX_GENPRO_DOC_ON_CITIZENSHIP on GENPRO_DOC (CITIZENSHIP_ID)^
-- end GENPRO_DOC
-- begin GENPRO_ENTITY_FOR_CHECH_WORK_JSON_OBJECT
alter table GENPRO_ENTITY_FOR_CHECH_WORK_JSON_OBJECT add constraint FK_GENPRO_ENTITY_FOR_CHECH_WORK_JSON_OBJECT_ON_CITIZENSHIP foreign key (CITIZENSHIP_ID) references Country(ID)^
create index IDX_GENPRO_ENTITY_FOR_CHECH_WORK_JSON_OBJECT_ON_CITIZENSHIP on GENPRO_ENTITY_FOR_CHECH_WORK_JSON_OBJECT (CITIZENSHIP_ID)^
-- end GENPRO_ENTITY_FOR_CHECH_WORK_JSON_OBJECT
